version: 2.1

jobs:
  build:
    parallelism: 15
    docker:
      - image: ruby:latest
    steps:
      - checkout
      - run : |
               chmod +x rebuild.sh && ./rebuild.sh
  build2:
    parallelism: 15
    docker:
      - image: ruby:latest
    steps:
      - checkout
      - run : |
               chmod +x rebuild.sh && ./rebuild.sh

workflows:
  main:
    jobs:
      - build
      - build2
